version: "3.8"

services:
  # O Banco de Dados (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: urbanflex_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: urbanflex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # O Adminer (Interface visual para ver o banco no navegador)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
